# Generated by Django 4.2.11 on 2024-09-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='summary',
            field=models.CharField(max_length=20),
        ),
    ]
