# Generated by Django 4.2.11 on 2024-10-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='subscribed',
            new_name='subscribed_users',
        ),
    ]
