# Generated by Django 4.2.4 on 2024-11-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='Category',
        ),
    ]
