# Generated by Django 4.2.2 on 2024-09-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=50)),
                ('category_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('fixed_price', models.BooleanField(default=False)),
                ('pubdate', models.DateField()),
            ],
        ),
    ]
