# Generated by Django 4.2.8 on 2024-10-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommended',
            new_name='Recommend',
        ),
    ]
